### ISSUE TITLE
Migrate from hardhat-waffle

### ISSUE THREAD

**Issue by andrejrakic** [smartcontractkit/hardhat-starter-kit#112]
Hardhat's latest [release](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat@2.10.0) suggests migrating away from `hardhat-waffle` to `hardhat-toolbox`

**Comment by 0xZarko** [comment]
Hi @andrejrakic , are you on this? If not, I would be willing to do it, my first open-source contrib :)

**Comment by 0xZarko** [comment]
Thanks! I just did the PR, hoping for some feedback.

**Comment by adityabhattad2021** [comment]
Is this still open?
