### ISSUE TITLE
Add comments about pushing `mnemonic` and `private_key` up to github

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/hardhat-starter-kit#15]
Big, bold, tell users not to do it.

**Comment by whamsicore** [comment]
I'd like to help with this issue. As well as help improve documentation in general, as I am a user myself :-)

**Comment by pappas999** [comment]
awesome to hear @whamsicore! If you'd like to help with this, feel free to submit a PR. Also, if you like, you can share your repo on Twitter or on share in our [discord](https://discord.com/invite/aSK4zew) as part of our currently running Starter Kit Showcase initiative, it would be great to share your contribution to our kits with others! [More info](https://twitter.com/chainlink/status/1396976073888485376)

**Comment by pappas999** [comment]
this looks like it's been resolved. closing
