### ISSUE TITLE
Readme should default to the HRE

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/hardhat-starter-kit#23]
the hardhat runtime environment is perfect for testing and doing everything we need to do.

**Comment by plinki** [comment]
just to clarify, this means adjusting instructions from kovan to the local hardhat network?

**Comment by pappas999** [comment]
Hi @plinki , yes the README should prioritize the instructions/notes for the local hardhat network (after all, the default network is set to hardhat). However it should still contain notes and instructions for other networks as it does now, but maybe just ensure the local environment ones are first. Hope this helps

**Comment by PatrickAlphaC** [comment]
Closing, I think this has been addressed
