### ISSUE TITLE
Add tasks back in 

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/hardhat-starter-kit#35]
`npx hardhat request-random-number --contract` shouldn't be a plug-in. It abstracts how this task is happening and isn't something a lot of projects are necessarily going to use. We want to show users how to make this task. 
Please add this task back in.

In fact, the majority of these shouldn't be abstracted out. The only tasks that should be tasks are reading price feeds and funding LINK .

**Comment by fabioDMFerreira** [comment]
Fair point. I'll publish the plugin to fund LINK.

**Comment by pappas999** [comment]
this has been merged, closing
