### ISSUE TITLE
npm/yarn to install "chainlink-plugins-fund-link", but with following error

### ISSUE THREAD

**Issue by Bingyy** [smartcontractkit/hardhat-starter-kit#39]
## npm install
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@appliedblockchain/chainlink-plugins-fund-link/-/chainlink-plugins-fund-link-0.0.1.tgz
npm ERR! 404
npm ERR! 404  '@appliedblockchain/chainlink-plugins-fund-link@0.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'hardhat-starter-kit'

## yarn
error An unexpected error occurred: "https://registry.yarnpkg.com/@appliedblockchain%2fchainlink-plugins-fund-link: Not found".

**Comment by fabioDMFerreira** [comment]
The package is now public.

Thanks for reporting @Bingyy.

**Comment by pappas999** [comment]
Thanks for raising this @Bingyy . Let us know if still any issues and we'll re-open
