### ISSUE TITLE
Typescript edition of this starter kit anyone? 

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/hardhat-starter-kit#48]
Maybe we should do one?

What are people's thoughts? Something similar to https://github.com/PatrickAlphaC/decentralized-raffle perhaps?

**Comment by jdram62** [comment]
🐍

**Comment by Magofoco** [comment]
Hello!
Has anyone already started working on it?

**Comment by PatrickAlphaC** [comment]
Yes! It's almost done :) @andrejrakic

**Comment by PatrickAlphaC** [comment]
https://github.com/smartcontractkit/hardhat-starter-kit/tree/typescript

**Comment by StephenFluin** [comment]
https://blog.chain.link/hardhat-starter-kit-typescript/
