### ISSUE TITLE
Remove "Hardcoded" warning in `RandomNumberConsumer.sol` or clarify what it means

### ISSUE THREAD

**Issue by JayWelsh** [smartcontractkit/hardhat-starter-kit#55]
`hardhat-starter-kit/contracts/RandomNumberConsumer.sol` states:

```
/**
 * THIS IS AN EXAMPLE CONTRACT WHICH USES HARDCODED VALUES FOR CLARITY.
 * PLEASE DO NOT USE THIS CODE IN PRODUCTION.
 */
```

But it's unclear what it is referring to when it says "Hardcoded values", it doesn't look like there are any hardcoded values, and the contract appears to be fine for a production deployment aside from maybe also having a withdraw function for any LINK in the contract.

Am I missing something which makes this unsuitable for a production deployment (aside from the withdraw function)? Are there any hardcoded values here?

Link for clarity: https://github.com/smartcontractkit/hardhat-starter-kit/blob/main/contracts/RandomNumberConsumer.sol#L5-L8

**Comment by PatrickAlphaC** [comment]
Thanks for making this! You're right there really aren't any hardcoded values in here, we should remove.
