### ISSUE TITLE
CC0 licence?

### ISSUE THREAD

**Issue by voltrevo** [smartcontractkit/hardhat-starter-kit#60]
Hi there. I was wondering if you would consider switching to a public domain licence like [CC0](https://creativecommons.org/publicdomain/zero/1.0/) or the [unlicense](https://unlicense.org/)?

Complying with the MIT licence is often not too hard - if you're using a library then you have an exact copy and you simply preserve the licence declaration. Easy. Not so when creating a derivative work, and this is a template project so all usage is derivative in nature. How do you refer to the code that remains copied from here to attribute the MIT licence?

If a part of that project itself is used to create another derivative work, how is that author to know if they have used any of this project's code, and whether they are subject to its MIT licence? That downstream author, if paying attention to compliance, may be forced to write something like:

```
Though I am not aware of any specific examples, there may be portions of this   
project that are considered derivative of hardhat-starter-kit. The copyright       
for those portions would be held by pappas999 (c) 2021, and the MIT licence        
below would apply.

(MIT licence goes here)
```

IANAL, but to the best of my knowledge, project authors are required to do this kind of thing. I think it's a bit silly, and it would be better if we all stopped worrying about attribution in open source licences, and just committed the work to the public domain (assuming having other projects benefit from your work is the goal, of course).

Wdyt?

**Comment by PatrickAlphaC** [comment]
Thanks for bringing this up! @StephenFluin wondering if you have any insight here?

**Comment by StephenFluin** [comment]
The MIT license is often chosen purposefully so that derivative works remain open source. https://www.gnu.org/licenses/copyleft.en.html

**Comment by voltrevo** [comment]
> The MIT license is often chosen purposefully so that derivative works remain open source. https://www.gnu.org/licenses/copyleft.en.html

If that's the intention then wouldn't the GPL better serve that goal?

I'm not sure that MIT is intended to be copy-left in this way. My understanding is that MIT is permissive, promoting wide adoption, and the terms are there merely to disclaim liability and preserve some credit for the author, deliberately avoiding any additional restrictions on derivative works, since that would inhibit derivative works.

Of course, if you consider this copy-left aspect of the MIT licence to be a feature and not a bug, then I respect that. Personally though, it means I'd rather put together a hardhat project manually than use this template.
