### ISSUE TITLE
Premium and gas per link variable in the deploy mocks scripts should be clarified

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/hardhat-starter-kit#90]
Right now, we deploy the VRFCoordinatorV2Mock as such:

```javascript
    await deploy("VRFCoordinatorV2Mock", {
      from: deployer,
      log: true,
      args: [
        POINT_ONE_LINK,
        1e9, // 0.000000001 LINK per gas
      ],
    })
```

`POINT_ONE_LINK` and `1e9` are not descriptive for what each stands for, they should be something like:

```
BASE_FEE,
GAS_PRICE_LINK
```

Respectively, with a link explaining what each means.

**Comment by chabi87r** [comment]
hi Patrick I have a nice non-profit project that will help change this sick world, please take a look at my repo

**Comment by misterDre** [comment]
How would this look like for brownie. Currently trying to deploy the VRFCoordinatorV2Mock but dont know what to pass in for _baseFee and _gasPriceLink.

**Comment by pappas999** [comment]
hi @misterDre, if you have any questions related to the brownie starter kit, please raise a question on [stackoverflow](https://stackoverflow.com/questions/ask?tags=chainlink), tagging Chainlink.
