### ISSUE TITLE
How to Use Chainlink With Hardhat

### ISSUE THREAD

**Issue by jebitok-dev** [smartcontractkit/hardhat-starter-kit#92]
Suggesting an issue to have the GitHub repository on this [tutorial](https://blog.chain.link/using-chainlink-with-hardhat/) be replaced with this [one](https://github.com/smartcontractkit/hardhat-starter-kit/) as it is the latest hardhat-starter-kit and the one isn't being maintained anymore according to its ReadMe File and the repository name was changed to this one

**Comment by PatrickAlphaC** [comment]
Thanks for this!

**Comment by PatrickAlphaC** [comment]
Done!
