### ISSUE TITLE
Predictable number for testing

### ISSUE THREAD

**Issue by leovafme** [smartcontractkit/hardhat-starter-kit#96]
In the RandomNumberConsumerV2 unit test, the result of the number is validated with always being greater than zero.
At first it's fine. but how is it applied for the moment in which it must be tested with a winning or specific number?

`assert(firstRandomNumber.gt(ethers.constants.Zero))`

Is there any way to provide the number as in the v1 mock?

`it("Should successfully request a random number and get a result", async () => {
        const transaction = await randomNumberConsumer.getRandomNumber()
        const transactionReceipt = await transaction.wait(1)
        const requestId = transactionReceipt.events[0].topics[1]
        const randomValue = 777
        await vrfCoordinatorMock.callBackWithRandomness(
          requestId,
          randomValue,
          randomNumberConsumer.address
        )
        assert.equal((await randomNumberConsumer.randomResult()).toString(), randomValue)
 })`

**Comment by leovafme** [comment]
Hi @andrejrakic. Thank you very much for quick response.
I tried to do as you say but I can't find a solution to the dilemma. I have searched and I have not seen any place that has implemented this successfully.

Is there a repository or someone who has implemented it? Thanks.

**Comment by andrejrakic** [comment]
@leovafme, how about something like this? (Haven't had time to try it btw, this is just a pseudo-code)
```typescript
  const vrfConsumerBaseV2Mock: MockContract = await waffle.deployMockContract(
    deployer,
    VRF_CONSUMER_BASE_V2_ABI
  );
  
  const randomWords = [BigNumber.from(`777`)];
  
  vrfConsumerBaseV2Mock.mock.rawFulfillRandomWords(requestId, randomWords).returns();
  // or
  vrfConsumerBaseV2Mock.mock["rawFulfillRandomWords(uint256, uint256[])"].withArgs(requestId, randomWords).returns();
```

**Comment by leovafme** [comment]
Hi @andrejrakic thanks for the code snippet. I tests it.  the function rawFulfillRandomWords required OnlyCoordinatorCanFulfill(msg.sender, vrfCoordinator). I extended VRFCoordinatorV2Mock

```solidity
pragma solidity ^0.8.0;

import "@chainlink/contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol";

contract VRFCoordinatorV2MockHelper is VRFCoordinatorV2Mock {
    constructor(uint96 _baseFee, uint96 _gasPriceLink) VRFCoordinatorV2Mock(_baseFee, _gasPriceLink) {}

    receive() external payable {}
}
```
in test fund ether to VRFCoordinatorV2MockHelper  and use hardhat_impersonateAccount for call vrfConsumerBaseV2Mock
```solidity
await admin.sendTransaction({
  to: vrfCoordinatorV2Mock.address,
  value: ethers.utils.parseEther("5.0"),
});

await ethers.provider.send("hardhat_impersonateAccount", [vrfCoordinatorV2Mock.address]);
await ethers.provider.send("evm_mine")

const signer = await ethers.getSigner(vrfCoordinatorV2Mock.address);

const randomWords = [777, 778];

await randomNumberConsumerV2.connect(signer).rawFulfillRandomWords(requestId, randomWords);
```

this works for me, but is it the proper implementation? Thanks.
