### ISSUE TITLE
Fix in hardhat.config.js file

### ISSUE THREAD

**Issue by luislucena16** [smartcontractkit/hardhat-starter-kit#99]
hey @PatrickAlphaC I have a doubt about line 100, it is calling the RandomNumberConsumer but I should assign the V2 at the end of the name, please correct me if I am wrong.

![fix](https://user-images.githubusercontent.com/86749595/169756873-f6fc44e8-102b-493b-a0bf-16ee506673cd.png)

**Comment by zeuslawyer** [comment]
HI @luislucena16!  Can you please link to the file you're referring to?

thanks!

**Comment by luislucena16** [comment]
hi @zeuslawyer! Sure,  https://github.com/smartcontractkit/hardhat-starter-kit/blob/main/hardhat.config.js line 100.

**Comment by zeuslawyer** [comment]
@luislucena16  - no problem!

I believe what you're saying makes sense.  Do you want to submit a PR? In case you've never submitted one, you can fork this repo (it will be called the "upstream" repo) and then you can follow this process:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork


Let me know if you want to try that :)

**Comment by luislucena16** [comment]
yes of course, I will open the PR and make the changes!

thanks :) @zeuslawyer

**Comment by luislucena16** [comment]
hey @zeuslawyer I have already opened the PR, here is the link https://github.com/smartcontractkit/hardhat-starter-kit/pull/100

**Comment by zeuslawyer** [comment]
thanks @luislucena16 . PR approved. 

Appreciate your help!
